lab_title: "Brain Health Lab"
institution: "St. Francis Xavier University"
contact_email: "brainhealthlab@stfx.ca"
pi_email: "emazerol@stfx.ca"
instagram_url: "https://www.instagram.com/brainhealthlab_stfx/"
github_url: "https://github.com/brainhealthlabstfx"
